Fix of Helidon exception
Helidon attempts to register a config instance globally and gives exception:

ServiceRegistryException: Contract io.helidon.common.config.Config is not provided by any service in the registry

This is because the io.helidon.common.config.Config contract is not in the core registry and can't be added there. Maybe a Helidon bug or a problem in the integration to GlassFish